"""Per-timeframe state classification.

Turns one feature vector into a :class:`TimeframeState`: which way, how forcefully,
and how much to trust the reading — with the evidence that produced each.

**Why a weighted rule set rather than a fitted model.** This layer has no labels to
learn from. "The market was bullish on 4 March" is not an observable fact; it is an
interpretation, and any labels would be generated by rules anyway. Fitting a model to
rule-generated labels teaches it to imitate the rules while making them opaque, which
is strictly worse. Phase 6 introduces learned models where there *is* a ground truth
to learn against — the realised future return — and that is the honest place for them.

**Signals are grouped before weighting.** Trend, momentum, structure and volatility
each contribute once. Without grouping, the six moving-average comparisons would
drown out everything else purely by being numerous, and the classifier would become
an expensive way to ask whether price is above its averages.

**Disagreement inside a group lowers confidence rather than cancelling out.** If MACD
says up and RSI says down, the honest output is "unclear", not "neutral with high
confidence".
"""

from __future__ import annotations

from collections.abc import Mapping
from datetime import datetime

from mie.core.logging import get_logger
from mie.core.timeframes import Timeframe
from mie.state.types import Direction, Evidence, TimeframeState

log = get_logger(__name__)

__all__ = ["SignalGroup", "TimeframeClassifier"]

#: Relative weight of each signal group in the final score. Trend dominates because
#: the question this layer answers is directional; volatility does not vote on
#: direction at all and instead modulates confidence.
_GROUP_WEIGHTS: dict[str, float] = {
    "trend": 0.40,
    "momentum": 0.30,
    "structure": 0.20,
    "volume": 0.10,
}

#: ADX above this is a trending market; below it, directional signals mean much less.
_ADX_TREND = 25.0
_ADX_STRONG = 40.0

#: Ceiling on classifier confidence. A hand-weighted rule set is not an oracle: even
#: with every signal agreeing on clean data, the *rules themselves* carry irreducible
#: uncertainty, and reporting 1.00 would claim otherwise. Without this cap the ceiling
#: is reached routinely — clean trending data alone gets there — which would feed
#: unearned certainty straight into Phase 7's published confidence.
_MAX_CONFIDENCE = 0.90


class SignalGroup:
    """Accumulates evidence within one group and reduces it to a single vote."""

    def __init__(self, name: str) -> None:
        self.name = name
        self.evidence: list[Evidence] = []

    def add(self, label: str, contribution: float, detail: str = "", weight: float = 1.0) -> None:
        self.evidence.append(
            Evidence(
                label=label,
                detail=detail,
                contribution=max(-1.0, min(1.0, contribution)),
                weight=weight,
            )
        )

    @property
    def score(self) -> float:
        """Weighted mean contribution, in [-1, 1]."""
        if not self.evidence:
            return 0.0
        total_weight = sum(e.weight for e in self.evidence)
        if total_weight == 0:
            return 0.0
        return sum(e.contribution * e.weight for e in self.evidence) / total_weight

    @property
    def coherence(self) -> float:
        """How much the signals inside this group agree, in [0, 1].

        One dissenting signal among five is a different situation from a three-two
        split, and confidence should reflect that. Signals sitting near zero are
        treated as abstentions rather than as disagreement.
        """
        voting = [e for e in self.evidence if abs(e.contribution) > 0.05]
        if len(voting) < 2:
            return 1.0 if voting else 0.5
        positive = sum(e.weight for e in voting if e.contribution > 0)
        negative = sum(e.weight for e in voting if e.contribution < 0)
        total = positive + negative
        return abs(positive - negative) / total if total else 0.5

    def supporting(self, direction_sign: int) -> list[Evidence]:
        return [e for e in self.evidence if e.contribution * direction_sign > 0.05]

    def opposing(self, direction_sign: int) -> list[Evidence]:
        return [e for e in self.evidence if e.contribution * direction_sign < -0.05]


class TimeframeClassifier:
    """Classifies one timeframe from its feature vector."""

    def classify(
        self,
        asset: str,
        timeframe: Timeframe,
        features: Mapping[str, float],
        as_of: datetime,
        data_quality: float = 1.0,
    ) -> TimeframeState:
        groups = {
            "trend": self._trend(features),
            "momentum": self._momentum(features),
            "structure": self._structure(features),
            "volume": self._volume(features),
        }

        # Groups that produced no evidence must not silently vote zero: that would
        # drag the score toward neutral in proportion to how much data is missing,
        # which reads as "the market is calm" when it actually means "we do not know".
        active = {name: g for name, g in groups.items() if g.evidence}
        if not active:
            return TimeframeState(
                asset=asset.upper(),
                timeframe=timeframe,
                as_of=as_of,
                direction=Direction.NEUTRAL,
                strength=0.0,
                confidence=0.0,
                score=0.0,
                evidence=[],
                data_quality=data_quality,
                close=features.get("close"),
            )

        weight_total = sum(_GROUP_WEIGHTS[name] for name in active)
        score = sum(g.score * _GROUP_WEIGHTS[name] for name, g in active.items()) / weight_total
        direction = Direction.from_score(score)
        sign = direction.sign

        strength = self._strength(features, abs(score))
        confidence = self._confidence(
            active, weight_total, features, data_quality, abs(score)
        )

        evidence: list[Evidence] = []
        counter: list[Evidence] = []
        for group in active.values():
            evidence.extend(group.supporting(sign) if sign else [])
            counter.extend(group.opposing(sign) if sign else [])
        # With no directional call, everything that voted is context rather than
        # support, and presenting it as "supporting evidence" would be misleading.
        if not sign:
            evidence = [e for g in active.values() for e in g.evidence]

        return TimeframeState(
            asset=asset.upper(),
            timeframe=timeframe,
            as_of=as_of,
            direction=direction,
            strength=round(strength, 4),
            confidence=round(confidence, 4),
            score=round(score, 4),
            evidence=sorted(evidence, key=lambda e: -abs(e.contribution))[:8],
            counter_evidence=sorted(counter, key=lambda e: -abs(e.contribution))[:5],
            volatility_pct=features.get("realised_vol_20"),
            close=features.get("close"),
            data_quality=data_quality,
        )

    # ------------------------------------------------------------------- groups

    def _trend(self, f: Mapping[str, float]) -> SignalGroup:
        """Where price sits relative to its averages, and how those averages stack."""
        group = SignalGroup("trend")
        close = f.get("close")
        if close is None or close <= 0:
            return group

        # Price against each average, scaled by distance: 5% above the 200 is a
        # different statement from 0.1% above it.
        for key, weight in (("ema_21", 1.0), ("sma_50", 1.2), ("sma_200", 1.5)):
            level = f.get(key)
            if level is None or level <= 0:
                continue
            distance = (close - level) / level * 100.0
            group.add(
                f"price vs {key}",
                _squash(distance, scale=4.0),
                detail=f"{distance:+.2f}%",
                weight=weight,
            )

        # Moving-average stacking order: the classic definition of trend structure.
        fast, mid, slow = f.get("ema_21"), f.get("sma_50"), f.get("sma_200")
        if fast and mid and slow:
            if fast > mid > slow:
                group.add("moving averages stacked bullish", 0.8, "21 > 50 > 200", weight=1.5)
            elif fast < mid < slow:
                group.add("moving averages stacked bearish", -0.8, "21 < 50 < 200", weight=1.5)
            else:
                group.add("moving averages interleaved", 0.0, "no clean stack", weight=0.5)

        # ADX carries no direction of its own; the DI pair supplies it, and only
        # counts when ADX says there is a trend worth having a direction about.
        adx, plus_di, minus_di = f.get("adx_14.adx"), f.get("adx_14.plus_di"), f.get("adx_14.minus_di")
        if adx is not None and plus_di is not None and minus_di is not None:
            if adx >= _ADX_TREND:
                spread = (plus_di - minus_di) / max(plus_di + minus_di, 1e-9)
                magnitude = min(1.0, (adx - _ADX_TREND) / (_ADX_STRONG - _ADX_TREND) * 0.5 + 0.5)
                group.add(
                    "directional index",
                    spread * magnitude,
                    detail=f"ADX {adx:.0f}, +DI {plus_di:.0f} / -DI {minus_di:.0f}",
                    weight=1.3,
                )
            else:
                group.add(
                    "no trend strength",
                    0.0,
                    detail=f"ADX {adx:.0f} below {_ADX_TREND:.0f}",
                    weight=0.8,
                )
        return group

    def _momentum(self, f: Mapping[str, float]) -> SignalGroup:
        group = SignalGroup("momentum")

        rsi = f.get("rsi_14")
        if rsi is not None:
            # RSI is read as momentum around 50, not as a mean-reversion trigger.
            # "Overbought" markets keep rising for a long time, and trading the
            # extreme as a reversal signal is a well-known way to lose money in a
            # trend; the extremes are flagged as counter-evidence instead.
            group.add("RSI", _squash(rsi - 50.0, scale=20.0), detail=f"{rsi:.0f}", weight=1.2)
            if rsi >= 75:
                group.add("stretched to the upside", -0.25, f"RSI {rsi:.0f}", weight=0.6)
            elif rsi <= 25:
                group.add("stretched to the downside", 0.25, f"RSI {rsi:.0f}", weight=0.6)

        macd = f.get("macd_12_26_9.macd")
        signal = f.get("macd_12_26_9.signal")
        histogram = f.get("macd_12_26_9.histogram")
        if macd is not None and signal is not None and histogram is not None:
            close = f.get("close") or 1.0
            # Normalised by price so the reading is comparable across assets.
            group.add(
                "MACD vs signal",
                _squash(histogram / close * 100.0, scale=0.35),
                detail=f"histogram {histogram:+.4g}",
                weight=1.2,
            )
            group.add(
                "MACD sign",
                0.4 if macd > 0 else -0.4,
                detail="above zero" if macd > 0 else "below zero",
                weight=0.8,
            )

        roc = f.get("roc_10")
        if roc is not None:
            group.add("rate of change", _squash(roc, scale=3.0), detail=f"{roc:+.2f}%", weight=1.0)

        stoch_k = f.get("stoch_14.k")
        if stoch_k is not None:
            group.add(
                "stochastic", _squash(stoch_k - 50.0, scale=30.0), detail=f"%K {stoch_k:.0f}", weight=0.7
            )
        return group

    def _structure(self, f: Mapping[str, float]) -> SignalGroup:
        group = SignalGroup("structure")

        trend = f.get("structure_trend")
        if trend is not None:
            group.add(
                "swing structure",
                float(trend) * 0.85,
                detail={1.0: "higher highs and lows", -1.0: "lower highs and lows"}.get(
                    float(trend), "no clean structure"
                ),
                weight=1.5,
            )

        close = f.get("close")
        support, resistance = f.get("support"), f.get("resistance")
        if close and support and resistance and resistance > support:
            # Position within the support/resistance envelope: near resistance is
            # mildly bearish for continuation, near support mildly bullish.
            position = (close - support) / (resistance - support)
            group.add(
                "position in range",
                _squash((0.5 - position) * 2.0, scale=1.0) * 0.5,
                detail=f"{position:.0%} of the way to resistance",
                weight=0.8,
            )
        elif close and support and resistance is None:
            group.add("no resistance overhead", 0.3, "above all clustered levels", weight=0.7)
        elif close and resistance and support is None:
            group.add("no support beneath", -0.3, "below all clustered levels", weight=0.7)

        percent_b = f.get("bb_20.percent_b")
        if percent_b is not None:
            if percent_b > 1.0:
                group.add("closed above the upper band", 0.5, f"%b {percent_b:.2f}", weight=0.9)
            elif percent_b < 0.0:
                group.add("closed below the lower band", -0.5, f"%b {percent_b:.2f}", weight=0.9)
            else:
                group.add(
                    "position in bands",
                    (percent_b - 0.5) * 0.8,
                    detail=f"%b {percent_b:.2f}",
                    weight=0.7,
                )

        vwap_distance = f.get("vwap.vwap_distance_pct")
        if vwap_distance is not None:
            group.add(
                "price vs VWAP",
                _squash(vwap_distance, scale=2.0) * 0.6,
                detail=f"{vwap_distance:+.2f}%",
                weight=0.8,
            )
        return group

    def _volume(self, f: Mapping[str, float]) -> SignalGroup:
        group = SignalGroup("volume")

        obv_change = f.get("obv.obv_change")
        volume = f.get("volume")
        if obv_change is not None and volume and volume > 0:
            # Normalised by recent bar volume so the reading is scale-free.
            group.add(
                "on-balance volume trend",
                _squash(obv_change / (volume * 20.0), scale=0.5),
                detail=f"{obv_change:+,.0f}",
                weight=1.0,
            )

        change = f.get("change_pct")
        if change is not None:
            group.add("last bar", _squash(change, scale=1.5) * 0.5, detail=f"{change:+.2f}%", weight=0.6)
        return group

    # -------------------------------------------------------------- aggregation

    def _strength(self, f: Mapping[str, float], score_magnitude: float) -> float:
        """How forceful the move is, independent of direction.

        ADX is the natural measure where available; otherwise the magnitude of the
        directional score stands in for it.
        """
        adx = f.get("adx_14.adx")
        if adx is None:
            return score_magnitude
        trend_strength = min(1.0, max(0.0, (adx - 10.0) / 40.0))
        return round(0.6 * trend_strength + 0.4 * score_magnitude, 4)

    def _confidence(
        self,
        groups: dict[str, SignalGroup],
        weight_total: float,
        f: Mapping[str, float],
        data_quality: float,
        score_magnitude: float,
    ) -> float:
        """How much to trust this reading.

        Four independent reasons to doubt a classification, each multiplicative
        because any one of them alone is enough to make the reading unreliable:

        1. the signals inside each group disagree;
        2. some groups had no data at all;
        3. the overall score sits near zero, where the direction label is arbitrary;
        4. the underlying data is degraded — the Phase 1 trust score, arriving here.

        The product is then capped at :data:`_MAX_CONFIDENCE`, because a rule set that
        agrees with itself is still only a rule set.
        """
        coherence = sum(
            g.coherence * _GROUP_WEIGHTS[name] for name, g in groups.items()
        ) / weight_total
        coverage = weight_total / sum(_GROUP_WEIGHTS.values())
        # A near-zero score means the direction label is close to arbitrary, so
        # confidence in *that label* should be low even if the inputs are clean.
        decisiveness = min(1.0, 0.35 + score_magnitude * 1.6)

        confidence = (
            _MAX_CONFIDENCE
            * coherence
            * coverage
            * decisiveness
            * max(0.0, min(1.0, data_quality))
        )
        return max(0.0, min(_MAX_CONFIDENCE, confidence))


def _squash(value: float, scale: float) -> float:
    """Map an unbounded reading onto [-1, 1] with a soft knee.

    Linear clipping would treat a 4% and a 40% move as identical once past the
    threshold; this keeps extremes distinguishable while bounding the contribution.
    """
    if scale <= 0:
        return 0.0
    normalised = value / scale
    return normalised / (1.0 + abs(normalised))
